# 资源根目录
resource_root = resources/

# 日志配置 默认文件后缀.log
log_file = log/webserver
# 0 : DEBUG 1 : INFO 2 : WARN 3 : ERROR
log_level = 1
# 日志队列最大容量
log_queue_size = 1024
# 强制刷盘间隔（秒）
log_flush_interval = 3
# 网络配置
# 端口
port = 9999
# 连接超时时间（秒）
connection_timeout = 60

# 数据库配置
# 连接池大小（0 = 禁用数据库）
connection_pool_size = 16
db_host = 127.0.0.1
db_port = 3306
db_user = root
db_password = password
db_name = webserver
